name: Generate Installable ZIP
on:
  push:
    branches: [ main ] # O master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Zip
        run: zip -r stic_ClubsSocials_installable.zip . -x "*.git*" ".github*"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Module-Package
          path: stic_ClubsSocials_installable.zip
