name: Generate Release
on:
  push:
    tags:
      - 'v*' # Se activará cuando subas un tag que empiece por v (ej: v1.1)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip
        run: zip -r stic_ClubsSocials.zip . -x "*.git*" ".github*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: stic_ClubsSocials.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}